-- Migration: Seed meals with real data from Bombos 1 export
-- Replaces placeholder seed data in 005_meals.sql

DELETE FROM meals;

INSERT INTO meals (category, name) VALUES
  ('dinner', 'Potrawka'),
  ('dinner', 'Kotlety z fasoli'),
  ('dinner', 'Rolady z kurczaka z pesto'),
  ('dinner', 'Pad thai'),
  ('dinner', 'Makaron z łososiem'),
  ('dinner', 'Makaron z pesto'),
  ('dinner', 'Kopytka'),
  ('dinner', 'Burgery'),
  ('dinner', 'Kurczak sojowy'),
  ('dinner', 'Pierogi'),
  ('dinner', 'Kurczak ze szparagami'),
  ('dinner', 'Pyzy z farszem'),
  ('dinner', 'Ryż z warzywami'),
  ('dinner', 'Jajko sadzone'),
  ('dinner', 'Makaron z krewetkami'),
  ('dinner', 'Carbonara'),
  ('dinner', 'Łosoś na parze'),
  ('dinner', 'Zapiekanka makaronowa'),
  ('dinner', 'Pita z kurczakiem'),
  ('dinner', 'Ramen'),
  ('dinner', 'Łosoś z łódeczkami'),
  ('dinner', 'Placki ziemniaczane'),
  ('dinner', 'Indyk w sosie sojowo-chilli'),
  ('dinner', 'Paluszki rybne'),
  ('dinner', 'Ryba z grilla'),
  ('dinner', 'Szare kluchy'),
  ('dinner', 'Kurczak curry w mleku kokosowym'),
  ('dinner', 'Kotlety'),
  ('dinner', 'Steki'),
  ('dinner', 'Chalupas'),
  ('dinner', 'Gnocchi z kurczakiem w sosie grzybowym'),
  ('dinner', 'Pierogi z piekarnika'),
  ('dinner', 'Naleśniki ze szpinakiem'),
  ('supper', 'Warzywa z humusem'),
  ('supper', 'Tortille'),
  ('supper', 'Zupa'),
  ('supper', 'Frytki zapiekane'),
  ('supper', 'Płatki z mlekiem'),
  ('supper', 'Ślimaki'),
  ('supper', 'Zapieksy'),
  ('supper', 'Kanapki z makrelą w pomidorach'),
  ('supper', 'Sałatka z kukurydzą'),
  ('supper', 'Sałatka z brokułem'),
  ('supper', 'Kieszonki z brie'),
  ('supper', 'Racuchy'),
  ('supper', 'Śledzik'),
  ('supper', 'Pierogi'),
  ('supper', 'Pizza ze skyru'),
  ('supper', 'Frytki z batatów'),
  ('supper', 'Hot dogi'),
  ('supper', 'Shakshuka'),
  ('supper', 'Jajka faszerowane'),
  ('supper', 'Tosty');